
package com.cantero.quickbooks.ws;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "QBWebConnectorSvc", targetNamespace = "http://developer.intuit.com/", wsdlLocation = "http://developer.intuit.com/uploadedFiles/Support/QBWebConnectorSvc.wsdl")
public class QBWebConnectorSvc
    extends Service
{

    private final static URL QBWEBCONNECTORSVC_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.cantero.quickbooks.ws.QBWebConnectorSvc.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.cantero.quickbooks.ws.QBWebConnectorSvc.class.getResource(".");
            url = new URL(baseUrl, "http://developer.intuit.com/uploadedFiles/Support/QBWebConnectorSvc.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://developer.intuit.com/uploadedFiles/Support/QBWebConnectorSvc.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        QBWEBCONNECTORSVC_WSDL_LOCATION = url;
    }

    public QBWebConnectorSvc(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public QBWebConnectorSvc() {
        super(QBWEBCONNECTORSVC_WSDL_LOCATION, new QName("http://developer.intuit.com/", "QBWebConnectorSvc"));
    }

    /**
     * 
     * @return
     *     returns QBWebConnectorSvcSoap
     */
    @WebEndpoint(name = "QBWebConnectorSvcSoap")
    public QBWebConnectorSvcSoap getQBWebConnectorSvcSoap() {
        return super.getPort(new QName("http://developer.intuit.com/", "QBWebConnectorSvcSoap"), QBWebConnectorSvcSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns QBWebConnectorSvcSoap
     */
    @WebEndpoint(name = "QBWebConnectorSvcSoap")
    public QBWebConnectorSvcSoap getQBWebConnectorSvcSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://developer.intuit.com/", "QBWebConnectorSvcSoap"), QBWebConnectorSvcSoap.class, features);
    }

}
